functional:
  - Пользователь должен иметь возможность авторизоваться и зарегистриваться в системе
  - Пользователь должен иметь возможность создать новую игру или присоединиться к уже существующим играм
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Пользователь должен иметь возможность общаться с другими участникам сайта
  - Перевод сайта на другой язык должен быть корректным и полным
  - Сайт должен быть с интуитивно понятным интерфейсом, с простой навигацией
  - Пользователь должен иметь возможность связаться с тех.поддержкой при возникновении сложностей
  - Пользователь может просмотреть историю игр
  - Пользователь может заходить в свой личный профиль и менять данные
