functional:
  - Пользователь должен иметь возможность авторизоваться и зарегистриваться в системе
  - Пользователь должен иметь возможность создать новую игру или присоединиться к уже существующим играм
  - Пользователь должен иметь возможнось настроить свой профиль, сменить ник или пароль
  - Пользователь должен иметь возможнось вызвать на дуэль другого участника или сыграть с ботом
  - Пользователь должен иметь возможнось просматривать бои других участников
  - Пользователь должен иметь возможность просматривать историю игр
  - Пользователь должен иметь возможность отслеживать свой рейтинг среди других участников
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно протестировать на совместимость с последними версиями браузеров Google Chrome, Mozilla Firefox, Microsoft Edge, Safari, Яндекс Браузер и Браузер Опера
implicit:
  - Пользователь должен иметь возможность общаться с другими участникам сайта
  - Перевод сайта на другой язык должен быть корректным и полным
  - Сайт должен быть с интуитивно понятным интерфейсом, с простой навигацией
  - Пользователь должен иметь возможность связаться с тех.поддержкой при возникновении сложностей
  - Пользователь может просмотреть историю игр
  - Пользователь может заходить в свой личный профиль и менять данные
  - Пользователь может заходить в свой аккаунт разными способами
